### ISSUE TITLE
support for laravel 5.4.

### ISSUE THREAD

**Issue by meltzow** [maxbrokman/SafeQueue#11]
hi,
any plans for 5.4. or is it working too?

thx

**Comment by meltzow** [comment]
I tried it and after added to laravel 5.4 I got a exception at "php artisan":

  [ErrorException]                                                                                                         
  Declaration of MaxBrokman\SafeQueue\Worker::stop() should be compatible with Illuminate\Queue\Worker::stop($status = 0)

**Comment by maxbrokman** [comment]
Hi @meltzow I'm going to take a look at this today

**Comment by meltzow** [comment]
any news here?

**Comment by meltzow** [comment]
ah ok, you created a new version.thx. we will test it.

**Comment by meltzow** [comment]
thanks. it working for me now
