### ISSUE TITLE
safequeue not overwriting queue:work in lumen 5.5

### ISSUE THREAD

**Issue by pckuijper** [maxbrokman/SafeQueue#14]
Trying to implement the SafeQueue in lumen 5.5 I run into the issue that the command_name wont overwrite laravels own queue:work.

Config
```
'command_name' => false,
```
Bootstrap/App
```
$app->register(MaxBrokman\SafeQueue\DoctrineQueueProvider::class);
$app->configure('safequeue');
```

Could this be due to any 5.5 changes? and any ideas to a possible solution?

**Comment by knifesk** [comment]
Maybe it's a little late, but you should call the configure before the register.

```php
$app->configure('safequeue');
$app->register(MaxBrokman\SafeQueue\DoctrineQueueProvider::class);
```
